### ISSUE TITLE
Not obvious how to quit

### ISSUE THREAD

**Issue by libscott** [maxdee/alc_freeliner#1]
Run from Processing 3 under Linux, it wasn't obvious how to exit fullscreen mode. I tried Esc, q, ctrl+q, ctrl+c, x, etc.

It wasn't hard to get running, but it might be good to put a note in the README for newbs like me that you need to download Processing3, install a certain library, etc.

**Comment by maxdee** [comment]
Thanks for making the first report!
I will be adding install instructions in the doc of the next release. Currently freeliner can be closed with `alt-f4` or `cmd+w` on OSX. I could add something like `ctrl-q` but I dont see the point yet.
Otherwise you managed to make some fun mappings?
What I really need to do is some tutorial videos, which I may have to crowdfund for.

**Comment by ssadler** [comment]
> Otherwise you managed to make some fun mappings?

Unfortunately not; I appreciated finding the project but I was a bit annoyed with it after not being able to close the window. FWIW: I use Linux and (with the exception of Vim and Emacs) all programs can be closed with one of ctrl+q, ctrl+w, esc, q, etc... I ended up hitting ctrl+alt+f1 to switch out of X and kill it manually. After looking on Github for the quit shortcut I had run out of patience with it.

So, this is the point. Users are fickle!
