### ISSUE TITLE
Centre Reset

### ISSUE THREAD

**Issue by chelsealiggatt** [maxdee/alc_freeliner#3]
When loading a template, some centre points of groups are not loading correctly.

**Comment by maxdee** [comment]
Bun! nice to see you here. Can you provide a geometry.xml with which the bug occurs? 
(drag and drop into reply box :) 
Keep the bug reports coming!! They are super help-full.

**Comment by chelsealiggatt** [comment]
"Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."

**Comment by maxdee** [comment]
Ok so I tried out your file and everything seems fine. The closed shapes with `AD` are properly centered. What I noticed is that the groups with `E` which are unclosed, were centered. If you want to set a center for unclosed shapes, you can set the center and then uncenter it. The center point you define will always be the center, but the tag will not be on the center but on the last segment. So if you want to set the center of a group, but dont actualy want the offset to happen, center, then uncenter (`c`+rightclick, instead of leftclick).

**Comment by chelsealiggatt** [comment]
Ok I will try c+rightclick next time!

Will be making a new geometry tonight / tomorrow for Daome! Gonna try the
SVG loader, but if it doesn't work for some reason, will create another
stencil design out of poster board...

On Mon, May 23, 2016 at 6:01 PM, maxdee <notifications@github.com> wrote:

> Ok so I tried out your file and everything seems fine. The closed shapes
> with AD are properly centered. What I noticed is that the groups with E
> which are unclosed, were centered. If you want to set a center for unclosed
> shapes, you can set the center and then uncenter it. The center point you
> define will always be the center, but the tag will not be on the center but
> on the last segment. So if you want to set the center of a group, but dont
> actualy want the offset to happen, center, then uncenter (c+rightclick,
> instead of leftclick).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/maxdee/alc_freeliner/issues/3#issuecomment-221109527>
>



-- 
Chelsea Liggatt
www.chelsealiggatt.com
